### ISSUE TITLE
Restriction on items

### ISSUE THREAD

**Issue by gaveer** [kaelonR/WoW-BuyemAll-live#19]
Hello there @kaelonR 

can you add restriction on a non refundable items like : [Commendation of the Zandalar Tribe](https://www.wowhead.com/item=224570)
when i tried to buy the item and select the quantity of the item it Max out all and buy 250 without confirmation , 
i lost over 11K Time badges and cant refund them . open a ticket and the GM said he cant refund them >

**Comment by kaelonR** [comment]
Hi @gaveer,

The Zandalar Tribe commendations have a max stack size of 250, meaning you've bought one stack of these commendations. 

While I sympathise with you, I don't think it's realistic to put restrictions on non refundable items. 99% of items sold by vendors are non-refundable. This means I would have to put a restriction and/or a confirmation dialog on the vast majority of purchases that players make. I think the inconvenience of limiting or requiring confirmation on the vast majority of purchases outweigh the benefits of preventing the fringe edge case like this.

BuyEmAll by default *does* ask for confirmation if you're trying to buy more than one stack, but these commendations have a rather high stack count of 250 items per stack, which is why no confirmation was asked as buying less than a full stack is considered a trivial purchase in most cases. I agree that this one was not a trivial purchase, but I don't see a good place to draw a line on what is and is not a trivial purchase using the in-game data available. Best advice I can give you is to double check the amount you entered and the total cost displayed before clicking the "buy" button next time.
